# Generated by Django 3.2.14 on 2022-07-25 15:34

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0034_alter_fileattachment_mimetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigTemplateModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
                ),
                ("template", models.TextField()),
                ("context", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="extras.graphqlquery")),
            ],
            options={
                "ordering": ["name", "context"],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin),
        ),
    ]
